### ISSUE TITLE
getting error when first time setup language

### ISSUE THREAD

**Issue by vzankhana** [goru001/inltk#59]
Following exception is raised when I try to setup Gujarati language.
>>> from inltk.inltk import setup
>>> setup('gu')
Downloading Model. This might take time, depending on your internet connection. Please be patient.
We'll only do this for the first time.
Traceback (most recent call last):
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\aiohttp\connector.py", line 1001, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\aiohttp\connector.py", line 867, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\aiohttp\resolver.py", line 32, in resolve
    hostname, port, type=socket.SOCK_STREAM, family=family
  File "C:\Users\LENOVO\Anaconda3\lib\asyncio\base_events.py", line 784, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "C:\Users\LENOVO\Anaconda3\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\LENOVO\Anaconda3\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\inltk\inltk.py", line 33, in setup
    learn = loop.run_until_complete(asyncio.gather(*tasks))[0]
  File "C:\Users\LENOVO\Anaconda3\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\inltk\inltk.py", line 25, in download
    learn = await setup_language(language_code)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\inltk\download_assets.py", line 29, in setup_language
    await download_file(config['lm_model_url'], path/'models'/f'{language_code}', config["lm_model_file_name"])
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\inltk\download_assets.py", line 19, in download_file
    async with session.get(url) as response:
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\aiohttp\client.py", line 1124, in __aenter__
    self._resp = await self._coro
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\aiohttp\client.py", line 528, in _request
    req, traces=traces, timeout=real_timeout
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\aiohttp\connector.py", line 537, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\aiohttp\connector.py", line 894, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\LENOVO\Anaconda3\lib\site-packages\aiohttp\connector.py", line 1013, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.dropbox.com:443 ssl:default [getaddrinfo failed]
>>>                                                                                                                           
please help...

**Comment by vzankhana** [comment]
it seems I have openSSL problem on my windows 10. but not able to resolve it. can u please just help?

**Comment by vzankhana** [comment]
I have solved the problem. Thanks anyway.
