### ISSUE TITLE
Getting error while calling setup

### ISSUE THREAD

**Issue by N-E-W-T-O-N** [goru001/inltk#90]
When I try to call setup, the following error shows up.

```
from inltk.inltk import setup
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/newton/miniconda3/lib/python3.10/site-packages/inltk/inltk.py", line 11, in <module>
from inltk.tokenizer import LanguageTokenizer
File "/home/newton/miniconda3/lib/python3.10/site-packages/inltk/tokenizer.py", line 11, in <module>
class LanguageTokenizer(BaseTokenizer):
NameError: name 'BaseTokenizer' is not defined
```

**Comment by SmartManoj** [comment]
[fastai.text NameError: name 'BaseTokenizer' is not defined](https://stackoverflow.com/a/65376957)
